# Generated by Django 4.2.17 on 2025-01-02 12:42

from django.db import migrations
import identity.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=identity.models.LowerCaseEmailField(max_length=255, unique=True, verbose_name='Email address'),
        ),
    ]
