# Generated by Django 4.2.17 on 2025-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE VIEW invitee_event_view AS
            SELECT
                CONCAT(i.id, '_', e.id) AS id,
                i.id AS invitee_id,
                i.event_id,
                i.email,
                i.user_id,
                i.rsvp_status,
                e.title AS event_title,
                e.description AS event_description,
                e.location AS event_location,
                e.start_date,
                e.end_date,
                e.created_by_id AS event_created_by,
                e.created_at AS event_created_at,
                e.updated_at AS event_updated_at,
                u.first_name,
                u.last_name,
                u.email AS host_email
            FROM
                event_invitee i
            JOIN
                event_event e
            ON
                i.event_id = e.id
            JOIN
                identity_user u
            ON
                u.id = e.created_by_id;
        """,
        reverse_sql="DROP VIEW IF EXISTS invitee_event_view;",
        )
    ]