# Generated by Django 4.2.19 on 2025-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.EmailField(max_length=254),
        ),
    ]
