version: '3'

services:

  backend:
    build: ./backend
    container_name: boilerplate-backend
    stdin_open: true
    tty: true
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8001'
    env_file:
      - env.db
      - env.azure
    volumes:
      - ./backend/:/app/src/ # maps host directory to internal container directory
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    container_name: boilerplate-frontend
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8001:80
      - 3000:8080
    depends_on:
      - backend
      - frontend
    networks:
      - nginx_network
    environment:
      - NGINX_WEB_SOCKETS_ENABLED=true

  postgres:
    image: postgres:15
    env_file:
      - env.db
    networks:
      - postgres_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - nginx_network
      - postgres_network  

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  postgres_volume:
  frontend_volume:
