services:

  backend:
    build: ./backend
    stdin_open: true
    tty: true
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8001'
    env_file:
      - env.db
      - env.azure
    volumes:
      - ./backend/:/app/src/ # maps host directory to internal container directory
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    command: sh -c "npm ci && npm run dev"
#    stdin_open: true
#    tty: true
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8001:80
      - 5173:8080
    depends_on:
      - backend
      - frontend
    networks:
      - nginx_network

  postgres:
    image: postgres:15
    env_file:
      - env.db
    networks:
      - postgres_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  postgres_volume:
  frontend_node_modules:
